<!DOCTYPE html>
<html lang="{{ $export->locale }}" dir="{{ $isRtl ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8">
    <title>{{ $export->title }}</title>
    <style>
        body {
            font-family: {{ $isRtl ? 'DejaVu Sans, sans-serif' : 'serif' }};
            margin: 0;
            padding: 40px;
            color: #1f2937;
            background: #fff;
            direction: {{ $isRtl ? 'rtl' : 'ltr' }};
        }
        .cover {
            text-align: center;
            padding: 100px 20px;
            border-bottom: 2px solid #f43f5e;
            page-break-after: always;
        }
        .cover h1 {
            font-size: 36px;
            color: #e11d48;
            margin-bottom: 10px;
        }
        .cover p {
            font-size: 16px;
            color: #6b7280;
        }
        .entry {
            margin-bottom: 40px;
            page-break-inside: avoid;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 20px;
        }
        .entry-date {
            font-size: 12px;
            color: #f43f5e;
            font-weight: bold;
            text-transform: uppercase;
        }
        .entry-title {
            font-size: 22px;
            margin: 5px 0 15px 0;
            color: #111827;
        }
        .entry-body {
            font-size: 14px;
            line-height: 1.6;
            white-space: pre-wrap;
        }
        .meta-info {
            font-size: 12px;
            color: #9ca3af;
            margin-top: 10px;
        }
        .event-item {
            background: #fff1f2;
            padding: 12px 16px;
            border-radius: 8px;
            margin-bottom: 15px;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
            margin-top: 50px;
        }
    </style>
</head>
<body>
    <div class="cover">
        <h1>{{ $export->title }}</h1>
        <p>{{ $user->name }}'s Memory Book</p>
        @if($export->date_from || $export->date_to)
            <p>{{ $export->date_from?->format('F d, Y') ?? 'Start' }} — {{ $export->date_to?->format('F d, Y') ?? 'Present' }}</p>
        @endif
    </div>

    @if(count($events) > 0)
        <h2>{{ $isRtl ? 'الأحداث والمناسبات' : 'Milestones & Events' }}</h2>
        @foreach($events as $event)
            <div class="event-item">
                <strong>{{ $event->event_date->format('Y-m-d') }}</strong> — {{ $event->title }}
                @if($event->description)<p style="margin: 4px 0 0 0; font-size: 13px;">{{ $event->description }}</p>@endif
            </div>
        @endforeach
        <hr style="margin: 30px 0; border: 0; border-top: 1px solid #f3f4f6;">
    @endif

    <h2>{{ $isRtl ? 'المذكرات' : 'Journal Memories' }}</h2>

    @forelse($entries as $entry)
        <div class="entry">
            <div class="entry-date">{{ $entry->entry_date->format('F d, Y') }}</div>
            <h3 class="entry-title">{{ $entry->title }}</h3>
            <div class="entry-body">
                @foreach($entry->blocks as $block)
                    <p>{{ $block->content_json['text'] ?? '' }}</p>
                @endforeach
            </div>
            <div class="meta-info">
                @if($entry->mood) {{ $isRtl ? 'المزاج:' : 'Mood:' }} {{ $entry->mood->value }} | @endif
                @if($entry->location_name) {{ $isRtl ? 'الموقع:' : 'Location:' }} {{ $entry->location_name }} @endif
            </div>
        </div>
    @empty
        <p>{{ $isRtl ? 'لا توجد مذكرات في هذه الفترة.' : 'No journal memories recorded in this date range.' }}</p>
    @endforelse

    <div class="footer">
        Generated by Mementra on {{ now()->format('F d, Y') }}
    </div>
</body>
</html>
